// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: grpcapi_ratelimiter.proto

package ratelimiter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_grpcapi_ratelimiter_proto protoreflect.FileDescriptor

var file_grpcapi_ratelimiter_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x70, 0x6f, 0x6c,
	0x61, 0x72, 0x69, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x76, 0x32, 0x1a, 0x11,
	0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x32, 0xc8, 0x01, 0x0a, 0x0d, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x47,
	0x52, 0x50, 0x43, 0x12, 0x5a, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x23,
	0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e,
	0x76, 0x32, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x2e, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12,
	0x5b, 0x0a, 0x0a, 0x54, 0x69, 0x6d, 0x65, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x12, 0x24, 0x2e,
	0x70, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x76,
	0x32, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x2e, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x41, 0x64, 0x6a, 0x75,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0xad, 0x01, 0x0a,
	0x49, 0x69, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6c, 0x61, 0x74, 0x74, 0x69,
	0x63, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x6f, 0x6c, 0x65, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x72,
	0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x42, 0x12, 0x52, 0x61, 0x74, 0x65,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5a, 0x4c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6c, 0x65, 0x2d,
	0x69, 0x6f, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x2f, 0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var file_grpcapi_ratelimiter_proto_goTypes = []interface{}{
	(*RateLimitRequest)(nil),   // 0: polaris.metric.v2.RateLimitRequest
	(*TimeAdjustRequest)(nil),  // 1: polaris.metric.v2.TimeAdjustRequest
	(*RateLimitResponse)(nil),  // 2: polaris.metric.v2.RateLimitResponse
	(*TimeAdjustResponse)(nil), // 3: polaris.metric.v2.TimeAdjustResponse
}
var file_grpcapi_ratelimiter_proto_depIdxs = []int32{
	0, // 0: polaris.metric.v2.RateLimitGRPC.Service:input_type -> polaris.metric.v2.RateLimitRequest
	1, // 1: polaris.metric.v2.RateLimitGRPC.TimeAdjust:input_type -> polaris.metric.v2.TimeAdjustRequest
	2, // 2: polaris.metric.v2.RateLimitGRPC.Service:output_type -> polaris.metric.v2.RateLimitResponse
	3, // 3: polaris.metric.v2.RateLimitGRPC.TimeAdjust:output_type -> polaris.metric.v2.TimeAdjustResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcapi_ratelimiter_proto_init() }
func file_grpcapi_ratelimiter_proto_init() {
	if File_grpcapi_ratelimiter_proto != nil {
		return
	}
	file_ratelimiter_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcapi_ratelimiter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcapi_ratelimiter_proto_goTypes,
		DependencyIndexes: file_grpcapi_ratelimiter_proto_depIdxs,
	}.Build()
	File_grpcapi_ratelimiter_proto = out.File
	file_grpcapi_ratelimiter_proto_rawDesc = nil
	file_grpcapi_ratelimiter_proto_goTypes = nil
	file_grpcapi_ratelimiter_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RateLimitGRPCClient is the client API for RateLimitGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RateLimitGRPCClient interface {
	// 限流接口
	Service(ctx context.Context, opts ...grpc.CallOption) (RateLimitGRPC_ServiceClient, error)
	// 时间对齐接口
	TimeAdjust(ctx context.Context, in *TimeAdjustRequest, opts ...grpc.CallOption) (*TimeAdjustResponse, error)
}

type rateLimitGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRateLimitGRPCClient(cc grpc.ClientConnInterface) RateLimitGRPCClient {
	return &rateLimitGRPCClient{cc}
}

func (c *rateLimitGRPCClient) Service(ctx context.Context, opts ...grpc.CallOption) (RateLimitGRPC_ServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RateLimitGRPC_serviceDesc.Streams[0], "/polaris.metric.v2.RateLimitGRPC/Service", opts...)
	if err != nil {
		return nil, err
	}
	x := &rateLimitGRPCServiceClient{stream}
	return x, nil
}

type RateLimitGRPC_ServiceClient interface {
	Send(*RateLimitRequest) error
	Recv() (*RateLimitResponse, error)
	grpc.ClientStream
}

type rateLimitGRPCServiceClient struct {
	grpc.ClientStream
}

func (x *rateLimitGRPCServiceClient) Send(m *RateLimitRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rateLimitGRPCServiceClient) Recv() (*RateLimitResponse, error) {
	m := new(RateLimitResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rateLimitGRPCClient) TimeAdjust(ctx context.Context, in *TimeAdjustRequest, opts ...grpc.CallOption) (*TimeAdjustResponse, error) {
	out := new(TimeAdjustResponse)
	err := c.cc.Invoke(ctx, "/polaris.metric.v2.RateLimitGRPC/TimeAdjust", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateLimitGRPCServer is the server API for RateLimitGRPC service.
type RateLimitGRPCServer interface {
	// 限流接口
	Service(RateLimitGRPC_ServiceServer) error
	// 时间对齐接口
	TimeAdjust(context.Context, *TimeAdjustRequest) (*TimeAdjustResponse, error)
}

// UnimplementedRateLimitGRPCServer can be embedded to have forward compatible implementations.
type UnimplementedRateLimitGRPCServer struct {
}

func (*UnimplementedRateLimitGRPCServer) Service(RateLimitGRPC_ServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method Service not implemented")
}
func (*UnimplementedRateLimitGRPCServer) TimeAdjust(context.Context, *TimeAdjustRequest) (*TimeAdjustResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimeAdjust not implemented")
}

func RegisterRateLimitGRPCServer(s *grpc.Server, srv RateLimitGRPCServer) {
	s.RegisterService(&_RateLimitGRPC_serviceDesc, srv)
}

func _RateLimitGRPC_Service_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RateLimitGRPCServer).Service(&rateLimitGRPCServiceServer{stream})
}

type RateLimitGRPC_ServiceServer interface {
	Send(*RateLimitResponse) error
	Recv() (*RateLimitRequest, error)
	grpc.ServerStream
}

type rateLimitGRPCServiceServer struct {
	grpc.ServerStream
}

func (x *rateLimitGRPCServiceServer) Send(m *RateLimitResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rateLimitGRPCServiceServer) Recv() (*RateLimitRequest, error) {
	m := new(RateLimitRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RateLimitGRPC_TimeAdjust_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeAdjustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimitGRPCServer).TimeAdjust(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/polaris.metric.v2.RateLimitGRPC/TimeAdjust",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimitGRPCServer).TimeAdjust(ctx, req.(*TimeAdjustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RateLimitGRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "polaris.metric.v2.RateLimitGRPC",
	HandlerType: (*RateLimitGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TimeAdjust",
			Handler:    _RateLimitGRPC_TimeAdjust_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Service",
			Handler:       _RateLimitGRPC_Service_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpcapi_ratelimiter.proto",
}
