// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: bootstrap.proto

package sidecar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_HTTP        Protocol = 1
	Protocol_PROTOCOL_GRPC        Protocol = 2
	Protocol_PROTOCOL_DUBBO       Protocol = 3
	Protocol_PROTOCOL_THRIFT      Protocol = 4
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_HTTP",
		2: "PROTOCOL_GRPC",
		3: "PROTOCOL_DUBBO",
		4: "PROTOCOL_THRIFT",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_HTTP":        1,
		"PROTOCOL_GRPC":        2,
		"PROTOCOL_DUBBO":       3,
		"PROTOCOL_THRIFT":      4,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_bootstrap_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_bootstrap_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{0}
}

type LocalServiceState int32

const (
	LocalServiceState_LOCAL_SERVICE_STATE_UNSPECIFIED  LocalServiceState = 0
	LocalServiceState_LOCAL_SERVICE_STATE_REGISTERED   LocalServiceState = 1
	LocalServiceState_LOCAL_SERVICE_STATE_UNREGISTERED LocalServiceState = 2
	LocalServiceState_LOCAL_SERVICE_STATE_REJECTED     LocalServiceState = 3
)

// Enum value maps for LocalServiceState.
var (
	LocalServiceState_name = map[int32]string{
		0: "LOCAL_SERVICE_STATE_UNSPECIFIED",
		1: "LOCAL_SERVICE_STATE_REGISTERED",
		2: "LOCAL_SERVICE_STATE_UNREGISTERED",
		3: "LOCAL_SERVICE_STATE_REJECTED",
	}
	LocalServiceState_value = map[string]int32{
		"LOCAL_SERVICE_STATE_UNSPECIFIED":  0,
		"LOCAL_SERVICE_STATE_REGISTERED":   1,
		"LOCAL_SERVICE_STATE_UNREGISTERED": 2,
		"LOCAL_SERVICE_STATE_REJECTED":     3,
	}
)

func (x LocalServiceState) Enum() *LocalServiceState {
	p := new(LocalServiceState)
	*p = x
	return p
}

func (x LocalServiceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocalServiceState) Descriptor() protoreflect.EnumDescriptor {
	return file_bootstrap_proto_enumTypes[1].Descriptor()
}

func (LocalServiceState) Type() protoreflect.EnumType {
	return &file_bootstrap_proto_enumTypes[1]
}

func (x LocalServiceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocalServiceState.Descriptor instead.
func (LocalServiceState) EnumDescriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{1}
}

type ClientHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SdkLanguage        string     `protobuf:"bytes,1,opt,name=sdk_language,json=sdkLanguage,proto3" json:"sdk_language,omitempty"`
	SdkVersion         string     `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	SupportedProtocols []Protocol `protobuf:"varint,3,rep,packed,name=supported_protocols,json=supportedProtocols,proto3,enum=pole.sidecar.v1.Protocol" json:"supported_protocols,omitempty"`
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetSdkLanguage() string {
	if x != nil {
		return x.SdkLanguage
	}
	return ""
}

func (x *ClientHello) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ClientHello) GetSupportedProtocols() []Protocol {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

type ClientEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*ClientEvent_Hello
	//	*ClientEvent_RegisterLocalService
	//	*ClientEvent_UnregisterLocalService
	Event isClientEvent_Event `protobuf_oneof:"event"`
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (m *ClientEvent) GetEvent() isClientEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ClientEvent) GetHello() *ClientHello {
	if x, ok := x.GetEvent().(*ClientEvent_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *ClientEvent) GetRegisterLocalService() *LocalServiceRegistration {
	if x, ok := x.GetEvent().(*ClientEvent_RegisterLocalService); ok {
		return x.RegisterLocalService
	}
	return nil
}

func (x *ClientEvent) GetUnregisterLocalService() *LocalServiceUnregistration {
	if x, ok := x.GetEvent().(*ClientEvent_UnregisterLocalService); ok {
		return x.UnregisterLocalService
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_Hello struct {
	Hello *ClientHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientEvent_RegisterLocalService struct {
	RegisterLocalService *LocalServiceRegistration `protobuf:"bytes,2,opt,name=register_local_service,json=registerLocalService,proto3,oneof"`
}

type ClientEvent_UnregisterLocalService struct {
	UnregisterLocalService *LocalServiceUnregistration `protobuf:"bytes,3,opt,name=unregister_local_service,json=unregisterLocalService,proto3,oneof"`
}

func (*ClientEvent_Hello) isClientEvent_Event() {}

func (*ClientEvent_RegisterLocalService) isClientEvent_Event() {}

func (*ClientEvent_UnregisterLocalService) isClientEvent_Event() {}

type Listener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=pole.sidecar.v1.Protocol" json:"protocol,omitempty"`
	Port     uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Listener) Reset() {
	*x = Listener{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listener) ProtoMessage() {}

func (x *Listener) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listener.ProtoReflect.Descriptor instead.
func (*Listener) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{2}
}

func (x *Listener) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *Listener) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ListenerSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// These listeners are loopback-only outbound listeners used by the local
	// Thin SDK. Ingress listeners are never exposed through bootstrap.
	Listeners []*Listener `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
}

func (x *ListenerSnapshot) Reset() {
	*x = ListenerSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListenerSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerSnapshot) ProtoMessage() {}

func (x *ListenerSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerSnapshot.ProtoReflect.Descriptor instead.
func (*ListenerSnapshot) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{3}
}

func (x *ListenerSnapshot) GetListeners() []*Listener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

type LocalServiceRegistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Stable and unique within one OpenControlSession stream.
	RegistrationId string   `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Namespace      string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service        string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Protocol       Protocol `protobuf:"varint,4,opt,name=protocol,proto3,enum=pole.sidecar.v1.Protocol" json:"protocol,omitempty"`
	// The Sidecar always connects to this port through 127.0.0.1.
	LocalPort uint32 `protobuf:"varint,5,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
}

func (x *LocalServiceRegistration) Reset() {
	*x = LocalServiceRegistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalServiceRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalServiceRegistration) ProtoMessage() {}

func (x *LocalServiceRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalServiceRegistration.ProtoReflect.Descriptor instead.
func (*LocalServiceRegistration) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{4}
}

func (x *LocalServiceRegistration) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *LocalServiceRegistration) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LocalServiceRegistration) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LocalServiceRegistration) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *LocalServiceRegistration) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

type LocalServiceUnregistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegistrationId string `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
}

func (x *LocalServiceUnregistration) Reset() {
	*x = LocalServiceUnregistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalServiceUnregistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalServiceUnregistration) ProtoMessage() {}

func (x *LocalServiceUnregistration) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalServiceUnregistration.ProtoReflect.Descriptor instead.
func (*LocalServiceUnregistration) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{5}
}

func (x *LocalServiceUnregistration) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

type LocalServiceStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegistrationId string            `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	State          LocalServiceState `protobuf:"varint,2,opt,name=state,proto3,enum=pole.sidecar.v1.LocalServiceState" json:"state,omitempty"`
	Message        string            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LocalServiceStatus) Reset() {
	*x = LocalServiceStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalServiceStatus) ProtoMessage() {}

func (x *LocalServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalServiceStatus.ProtoReflect.Descriptor instead.
func (*LocalServiceStatus) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{6}
}

func (x *LocalServiceStatus) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *LocalServiceStatus) GetState() LocalServiceState {
	if x != nil {
		return x.State
	}
	return LocalServiceState_LOCAL_SERVICE_STATE_UNSPECIFIED
}

func (x *LocalServiceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SidecarEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*SidecarEvent_ListenerSnapshot
	//	*SidecarEvent_LocalServiceStatus
	Event isSidecarEvent_Event `protobuf_oneof:"event"`
}

func (x *SidecarEvent) Reset() {
	*x = SidecarEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bootstrap_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SidecarEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidecarEvent) ProtoMessage() {}

func (x *SidecarEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidecarEvent.ProtoReflect.Descriptor instead.
func (*SidecarEvent) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{7}
}

func (m *SidecarEvent) GetEvent() isSidecarEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *SidecarEvent) GetListenerSnapshot() *ListenerSnapshot {
	if x, ok := x.GetEvent().(*SidecarEvent_ListenerSnapshot); ok {
		return x.ListenerSnapshot
	}
	return nil
}

func (x *SidecarEvent) GetLocalServiceStatus() *LocalServiceStatus {
	if x, ok := x.GetEvent().(*SidecarEvent_LocalServiceStatus); ok {
		return x.LocalServiceStatus
	}
	return nil
}

type isSidecarEvent_Event interface {
	isSidecarEvent_Event()
}

type SidecarEvent_ListenerSnapshot struct {
	ListenerSnapshot *ListenerSnapshot `protobuf:"bytes,1,opt,name=listener_snapshot,json=listenerSnapshot,proto3,oneof"`
}

type SidecarEvent_LocalServiceStatus struct {
	LocalServiceStatus *LocalServiceStatus `protobuf:"bytes,2,opt,name=local_service_status,json=localServiceStatus,proto3,oneof"`
}

func (*SidecarEvent_ListenerSnapshot) isSidecarEvent_Event() {}

func (*SidecarEvent_LocalServiceStatus) isSidecarEvent_Event() {}

var File_bootstrap_proto protoreflect.FileDescriptor

var file_bootstrap_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x70, 0x6f, 0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e,
	0x76, 0x31, 0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x64, 0x6b, 0x5f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x64, 0x6b, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x64, 0x6b, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x64, 0x6b, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x13, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63,
	0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x12,
	0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x73, 0x22, 0x98, 0x02, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48,
	0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x61, 0x0a, 0x16, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x6f, 0x6c, 0x65, 0x2e,
	0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x14, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x18, 0x75,
	0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x70, 0x6f, 0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x16, 0x75, 0x6e,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x55, 0x0a,
	0x08, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x6f,
	0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x22, 0x4b, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f,
	0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x73, 0x22, 0xd1, 0x01, 0x0a, 0x18, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27,
	0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x35, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x45, 0x0a, 0x1a, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x91, 0x01, 0x0a,
	0x12, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x70, 0x6f,
	0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0xc2, 0x01, 0x0a, 0x0c, 0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x50, 0x0a, 0x11, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x73, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70,
	0x6f, 0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x48,
	0x00, 0x52, 0x10, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x57, 0x0a, 0x14, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x70, 0x6f, 0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x12, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x07, 0x0a, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2a, 0x73, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x50,
	0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x48, 0x54, 0x54, 0x50, 0x10, 0x01, 0x12, 0x11,
	0x0a, 0x0d, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x47, 0x52, 0x50, 0x43, 0x10,
	0x02, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x44, 0x55,
	0x42, 0x42, 0x4f, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f,
	0x4c, 0x5f, 0x54, 0x48, 0x52, 0x49, 0x46, 0x54, 0x10, 0x04, 0x2a, 0xa4, 0x01, 0x0a, 0x11, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x23, 0x0a, 0x1f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43,
	0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x22, 0x0a, 0x1e, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x5f, 0x53,
	0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x47,
	0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x24, 0x0a, 0x20, 0x4c, 0x4f, 0x43,
	0x41, 0x4c, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x55, 0x4e, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x20, 0x0a, 0x1c, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10,
	0x03, 0x32, 0xbc, 0x01, 0x0a, 0x15, 0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x4f,
	0x70, 0x65, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x70, 0x6f, 0x6c,
	0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x1a, 0x1d, 0x2e, 0x70, 0x6f, 0x6c, 0x65, 0x2e,
	0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x63,
	0x61, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x12, 0x55, 0x0a, 0x12, 0x4f, 0x70, 0x65,
	0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x2e, 0x70, 0x6f, 0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x1d, 0x2e,
	0x70, 0x6f, 0x6c, 0x65, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x8a, 0x01, 0x0a, 0x36, 0x69, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6c,
	0x61, 0x74, 0x74, 0x69, 0x63, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x6f, 0x6c, 0x65, 0x2e, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x42, 0x15, 0x53, 0x69, 0x64,
	0x65, 0x63, 0x61, 0x72, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x6f, 0x6c, 0x65, 0x2d, 0x69, 0x6f, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x67, 0x6f, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bootstrap_proto_rawDescOnce sync.Once
	file_bootstrap_proto_rawDescData = file_bootstrap_proto_rawDesc
)

func file_bootstrap_proto_rawDescGZIP() []byte {
	file_bootstrap_proto_rawDescOnce.Do(func() {
		file_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(file_bootstrap_proto_rawDescData)
	})
	return file_bootstrap_proto_rawDescData
}

var file_bootstrap_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bootstrap_proto_goTypes = []interface{}{
	(Protocol)(0),                      // 0: pole.sidecar.v1.Protocol
	(LocalServiceState)(0),             // 1: pole.sidecar.v1.LocalServiceState
	(*ClientHello)(nil),                // 2: pole.sidecar.v1.ClientHello
	(*ClientEvent)(nil),                // 3: pole.sidecar.v1.ClientEvent
	(*Listener)(nil),                   // 4: pole.sidecar.v1.Listener
	(*ListenerSnapshot)(nil),           // 5: pole.sidecar.v1.ListenerSnapshot
	(*LocalServiceRegistration)(nil),   // 6: pole.sidecar.v1.LocalServiceRegistration
	(*LocalServiceUnregistration)(nil), // 7: pole.sidecar.v1.LocalServiceUnregistration
	(*LocalServiceStatus)(nil),         // 8: pole.sidecar.v1.LocalServiceStatus
	(*SidecarEvent)(nil),               // 9: pole.sidecar.v1.SidecarEvent
}
var file_bootstrap_proto_depIdxs = []int32{
	0,  // 0: pole.sidecar.v1.ClientHello.supported_protocols:type_name -> pole.sidecar.v1.Protocol
	2,  // 1: pole.sidecar.v1.ClientEvent.hello:type_name -> pole.sidecar.v1.ClientHello
	6,  // 2: pole.sidecar.v1.ClientEvent.register_local_service:type_name -> pole.sidecar.v1.LocalServiceRegistration
	7,  // 3: pole.sidecar.v1.ClientEvent.unregister_local_service:type_name -> pole.sidecar.v1.LocalServiceUnregistration
	0,  // 4: pole.sidecar.v1.Listener.protocol:type_name -> pole.sidecar.v1.Protocol
	4,  // 5: pole.sidecar.v1.ListenerSnapshot.listeners:type_name -> pole.sidecar.v1.Listener
	0,  // 6: pole.sidecar.v1.LocalServiceRegistration.protocol:type_name -> pole.sidecar.v1.Protocol
	1,  // 7: pole.sidecar.v1.LocalServiceStatus.state:type_name -> pole.sidecar.v1.LocalServiceState
	5,  // 8: pole.sidecar.v1.SidecarEvent.listener_snapshot:type_name -> pole.sidecar.v1.ListenerSnapshot
	8,  // 9: pole.sidecar.v1.SidecarEvent.local_service_status:type_name -> pole.sidecar.v1.LocalServiceStatus
	2,  // 10: pole.sidecar.v1.SidecarSessionService.OpenSession:input_type -> pole.sidecar.v1.ClientHello
	3,  // 11: pole.sidecar.v1.SidecarSessionService.OpenControlSession:input_type -> pole.sidecar.v1.ClientEvent
	9,  // 12: pole.sidecar.v1.SidecarSessionService.OpenSession:output_type -> pole.sidecar.v1.SidecarEvent
	9,  // 13: pole.sidecar.v1.SidecarSessionService.OpenControlSession:output_type -> pole.sidecar.v1.SidecarEvent
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_bootstrap_proto_init() }
func file_bootstrap_proto_init() {
	if File_bootstrap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bootstrap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listener); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListenerSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrap_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalServiceRegistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrap_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalServiceUnregistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrap_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalServiceStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bootstrap_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SidecarEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bootstrap_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ClientEvent_Hello)(nil),
		(*ClientEvent_RegisterLocalService)(nil),
		(*ClientEvent_UnregisterLocalService)(nil),
	}
	file_bootstrap_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*SidecarEvent_ListenerSnapshot)(nil),
		(*SidecarEvent_LocalServiceStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bootstrap_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bootstrap_proto_goTypes,
		DependencyIndexes: file_bootstrap_proto_depIdxs,
		EnumInfos:         file_bootstrap_proto_enumTypes,
		MessageInfos:      file_bootstrap_proto_msgTypes,
	}.Build()
	File_bootstrap_proto = out.File
	file_bootstrap_proto_rawDesc = nil
	file_bootstrap_proto_goTypes = nil
	file_bootstrap_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SidecarSessionServiceClient is the client API for SidecarSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SidecarSessionServiceClient interface {
	// Legacy listener bootstrap retained for existing Thin SDKs.
	OpenSession(ctx context.Context, in *ClientHello, opts ...grpc.CallOption) (SidecarSessionService_OpenSessionClient, error)
	// Long-lived Thin SDK control session. The first ClientEvent must contain
	// ClientHello. Registrations belong to this stream and are removed when it
	// closes.
	OpenControlSession(ctx context.Context, opts ...grpc.CallOption) (SidecarSessionService_OpenControlSessionClient, error)
}

type sidecarSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSidecarSessionServiceClient(cc grpc.ClientConnInterface) SidecarSessionServiceClient {
	return &sidecarSessionServiceClient{cc}
}

func (c *sidecarSessionServiceClient) OpenSession(ctx context.Context, in *ClientHello, opts ...grpc.CallOption) (SidecarSessionService_OpenSessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SidecarSessionService_serviceDesc.Streams[0], "/pole.sidecar.v1.SidecarSessionService/OpenSession", opts...)
	if err != nil {
		return nil, err
	}
	x := &sidecarSessionServiceOpenSessionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SidecarSessionService_OpenSessionClient interface {
	Recv() (*SidecarEvent, error)
	grpc.ClientStream
}

type sidecarSessionServiceOpenSessionClient struct {
	grpc.ClientStream
}

func (x *sidecarSessionServiceOpenSessionClient) Recv() (*SidecarEvent, error) {
	m := new(SidecarEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sidecarSessionServiceClient) OpenControlSession(ctx context.Context, opts ...grpc.CallOption) (SidecarSessionService_OpenControlSessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SidecarSessionService_serviceDesc.Streams[1], "/pole.sidecar.v1.SidecarSessionService/OpenControlSession", opts...)
	if err != nil {
		return nil, err
	}
	x := &sidecarSessionServiceOpenControlSessionClient{stream}
	return x, nil
}

type SidecarSessionService_OpenControlSessionClient interface {
	Send(*ClientEvent) error
	Recv() (*SidecarEvent, error)
	grpc.ClientStream
}

type sidecarSessionServiceOpenControlSessionClient struct {
	grpc.ClientStream
}

func (x *sidecarSessionServiceOpenControlSessionClient) Send(m *ClientEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sidecarSessionServiceOpenControlSessionClient) Recv() (*SidecarEvent, error) {
	m := new(SidecarEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SidecarSessionServiceServer is the server API for SidecarSessionService service.
type SidecarSessionServiceServer interface {
	// Legacy listener bootstrap retained for existing Thin SDKs.
	OpenSession(*ClientHello, SidecarSessionService_OpenSessionServer) error
	// Long-lived Thin SDK control session. The first ClientEvent must contain
	// ClientHello. Registrations belong to this stream and are removed when it
	// closes.
	OpenControlSession(SidecarSessionService_OpenControlSessionServer) error
}

// UnimplementedSidecarSessionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSidecarSessionServiceServer struct {
}

func (*UnimplementedSidecarSessionServiceServer) OpenSession(*ClientHello, SidecarSessionService_OpenSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (*UnimplementedSidecarSessionServiceServer) OpenControlSession(SidecarSessionService_OpenControlSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenControlSession not implemented")
}

func RegisterSidecarSessionServiceServer(s *grpc.Server, srv SidecarSessionServiceServer) {
	s.RegisterService(&_SidecarSessionService_serviceDesc, srv)
}

func _SidecarSessionService_OpenSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientHello)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SidecarSessionServiceServer).OpenSession(m, &sidecarSessionServiceOpenSessionServer{stream})
}

type SidecarSessionService_OpenSessionServer interface {
	Send(*SidecarEvent) error
	grpc.ServerStream
}

type sidecarSessionServiceOpenSessionServer struct {
	grpc.ServerStream
}

func (x *sidecarSessionServiceOpenSessionServer) Send(m *SidecarEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _SidecarSessionService_OpenControlSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SidecarSessionServiceServer).OpenControlSession(&sidecarSessionServiceOpenControlSessionServer{stream})
}

type SidecarSessionService_OpenControlSessionServer interface {
	Send(*SidecarEvent) error
	Recv() (*ClientEvent, error)
	grpc.ServerStream
}

type sidecarSessionServiceOpenControlSessionServer struct {
	grpc.ServerStream
}

func (x *sidecarSessionServiceOpenControlSessionServer) Send(m *SidecarEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sidecarSessionServiceOpenControlSessionServer) Recv() (*ClientEvent, error) {
	m := new(ClientEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SidecarSessionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pole.sidecar.v1.SidecarSessionService",
	HandlerType: (*SidecarSessionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenSession",
			Handler:       _SidecarSessionService_OpenSession_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OpenControlSession",
			Handler:       _SidecarSessionService_OpenControlSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bootstrap.proto",
}
