// This file is @generated by prost-build.
/// 限流请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateLimitRequest {
    /// 命令字
    #[prost(enumeration = "RateLimitCmd", tag = "1")]
    pub cmd: i32,
    /// 初始化请求
    #[prost(message, optional, tag = "2")]
    pub rate_limit_init_request: ::core::option::Option<RateLimitInitRequest>,
    /// 上报请求
    #[prost(message, optional, tag = "3")]
    pub rate_limit_report_request: ::core::option::Option<RateLimitReportRequest>,
    /// 批量初始化请求
    #[prost(message, optional, tag = "4")]
    pub rate_limit_batch_init_request: ::core::option::Option<RateLimitBatchInitRequest>,
}
/// 限流应答
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateLimitResponse {
    /// 命令字
    #[prost(enumeration = "RateLimitCmd", tag = "1")]
    pub cmd: i32,
    /// 初始化应答
    #[prost(message, optional, tag = "2")]
    pub rate_limit_init_response: ::core::option::Option<RateLimitInitResponse>,
    /// 上报应答
    #[prost(message, optional, tag = "3")]
    pub rate_limit_report_response: ::core::option::Option<RateLimitReportResponse>,
    /// 批量初始化应答
    #[prost(message, optional, tag = "4")]
    pub rate_limit_batch_init_response: ::core::option::Option<
        RateLimitBatchInitResponse,
    >,
}
/// 初始化请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateLimitInitRequest {
    /// 限流目标对象数据
    #[prost(message, optional, tag = "1")]
    pub target: ::core::option::Option<LimitTarget>,
    /// 客户端唯一标识
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    /// 限流规则信息
    #[prost(message, repeated, tag = "3")]
    pub totals: ::prost::alloc::vec::Vec<QuotaTotal>,
    /// 客户端可指定滑窗数，不指定用默认值
    #[prost(uint32, tag = "4")]
    pub slide_count: u32,
    /// 限流模式
    #[prost(enumeration = "Mode", tag = "5")]
    pub mode: i32,
}
/// 初始化应答
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateLimitInitResponse {
    /// 应答错误码
    #[prost(uint32, tag = "1")]
    pub code: u32,
    /// 限流目标对象，回传给客户端
    #[prost(message, optional, tag = "2")]
    pub target: ::core::option::Option<LimitTarget>,
    /// 客户端的标识，与clientId对应，一个server全局唯一，上报时候带入
    #[prost(uint32, tag = "3")]
    pub client_key: u32,
    /// 计数器的标识
    #[prost(message, repeated, tag = "5")]
    pub counters: ::prost::alloc::vec::Vec<QuotaCounter>,
    /// 实际滑窗个数
    #[prost(uint32, tag = "6")]
    pub slide_count: u32,
    /// 限流server绝对时间，单位ms
    #[prost(int64, tag = "7")]
    pub timestamp: i64,
}
/// 批量初始化请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateLimitBatchInitRequest {
    /// 每条规则汇总成一个Init请求
    #[prost(message, repeated, tag = "1")]
    pub request: ::prost::alloc::vec::Vec<RateLimitInitRequest>,
    /// 客户端唯一标识
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LabeledQuotaCounter {
    /// 自定义标签
    #[prost(string, tag = "1")]
    pub labels: ::prost::alloc::string::String,
    /// 计数器的标识
    #[prost(message, repeated, tag = "2")]
    pub counters: ::prost::alloc::vec::Vec<QuotaCounter>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchInitResult {
    /// 应答错误码
    #[prost(uint32, tag = "1")]
    pub code: u32,
    /// 限流目标对象，回传给客户端，labels为规则
    #[prost(message, optional, tag = "2")]
    pub target: ::core::option::Option<LimitTarget>,
    /// 计数器的标识
    #[prost(message, repeated, tag = "3")]
    pub counters: ::prost::alloc::vec::Vec<LabeledQuotaCounter>,
    /// 实际滑窗个数
    #[prost(uint32, tag = "4")]
    pub slide_count: u32,
}
/// 批量初始化应答
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateLimitBatchInitResponse {
    /// 应答错误码
    #[prost(uint32, tag = "1")]
    pub code: u32,
    /// 客户端的标识，与clientId对应，一个server全局唯一，上报时候带入
    #[prost(uint32, tag = "2")]
    pub client_key: u32,
    /// 限流server绝对时间，单位ms
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
    /// 批量初始化结果
    #[prost(message, repeated, tag = "4")]
    pub result: ::prost::alloc::vec::Vec<BatchInitResult>,
}
/// 限流上报请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateLimitReportRequest {
    /// 客户端标识
    #[prost(uint32, tag = "1")]
    pub client_key: u32,
    /// 已使用的配额数
    #[prost(message, repeated, tag = "2")]
    pub quota_uses: ::prost::alloc::vec::Vec<QuotaSum>,
    /// 配额发生的时间，单位ms
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
}
/// 限流上报应答
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateLimitReportResponse {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    /// 剩余配额数
    #[prost(message, repeated, tag = "2")]
    pub quota_lefts: ::prost::alloc::vec::Vec<QuotaLeft>,
    /// 限流server绝对时间，单位ms
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
}
/// 限流目标，针对哪部分数据进行限流
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LimitTarget {
    /// 命名空间
    #[prost(string, tag = "1")]
    pub namespace: ::prost::alloc::string::String,
    /// 服务名
    #[prost(string, tag = "2")]
    pub service: ::prost::alloc::string::String,
    /// 自定义标签
    #[prost(string, tag = "3")]
    pub labels: ::prost::alloc::string::String,
    /// 批量自定义标签
    #[prost(string, repeated, tag = "4")]
    pub labels_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 阈值配置的值
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuotaTotal {
    /// 阈值模式
    #[prost(enumeration = "QuotaMode", tag = "1")]
    pub mode: i32,
    /// 单位秒
    #[prost(uint32, tag = "2")]
    pub duration: u32,
    /// 限流阈值
    #[prost(uint32, tag = "3")]
    pub max_amount: u32,
}
/// 限流计数器
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuotaCounter {
    /// 单位秒
    #[prost(uint32, tag = "1")]
    pub duration: u32,
    /// bucket的标识，上报时候带入
    #[prost(uint32, tag = "2")]
    pub counter_key: u32,
    /// 剩余配额数，应答返回，允许为负数
    #[prost(int64, tag = "3")]
    pub left: i64,
    /// 实际限流模式
    #[prost(enumeration = "Mode", tag = "4")]
    pub mode: i32,
    /// 接入的客户端数量
    #[prost(uint32, tag = "5")]
    pub client_count: u32,
}
/// 客户端阈值使用统计
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuotaSum {
    /// 计数器的标识，一个server全局唯一，上报时候带入
    #[prost(uint32, tag = "1")]
    pub counter_key: u32,
    /// 已使用的配额数，上报时候带入
    #[prost(uint32, tag = "2")]
    pub used: u32,
    /// 被限流数，上报时候带入
    #[prost(uint32, tag = "3")]
    pub limited: u32,
}
/// 客户端阈值使用统计，由服务端返回
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QuotaLeft {
    /// 计数器的标识，一个server全局唯一，上报时候带入
    #[prost(uint32, tag = "1")]
    pub counter_key: u32,
    /// 剩余配额数，应答返回，允许为负数
    #[prost(int64, tag = "2")]
    pub left: i64,
    /// 当前限流模式
    #[prost(enumeration = "Mode", tag = "3")]
    pub mode: i32,
    /// 接入的客户端数量
    #[prost(uint32, tag = "4")]
    pub client_count: u32,
}
/// 时间点对齐的请求
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimeAdjustRequest {}
/// 时间点对齐的应答
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimeAdjustResponse {
    /// 服务器时间点，毫秒
    #[prost(int64, tag = "1")]
    pub server_timestamp: i64,
}
/// 命令字
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RateLimitCmd {
    Init = 0,
    Acquire = 1,
    BatchInit = 2,
    BatchAcquire = 3,
}
impl RateLimitCmd {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Init => "INIT",
            Self::Acquire => "ACQUIRE",
            Self::BatchInit => "BATCH_INIT",
            Self::BatchAcquire => "BATCH_ACQUIRE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INIT" => Some(Self::Init),
            "ACQUIRE" => Some(Self::Acquire),
            "BATCH_INIT" => Some(Self::BatchInit),
            "BATCH_ACQUIRE" => Some(Self::BatchAcquire),
            _ => None,
        }
    }
}
/// 限频模式
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Mode {
    /// 自适应模式，根据历史流量自动调整
    Adaptive = 0,
    /// 批量抢占模式，客户端进行拉取，Server返回全量剩余配额
    BatchOccupy = 1,
    /// 批量分摊模式，客户端进行拉取，Server按比例进行分摊
    BatchShare = 2,
}
impl Mode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Adaptive => "ADAPTIVE",
            Self::BatchOccupy => "BATCH_OCCUPY",
            Self::BatchShare => "BATCH_SHARE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ADAPTIVE" => Some(Self::Adaptive),
            "BATCH_OCCUPY" => Some(Self::BatchOccupy),
            "BATCH_SHARE" => Some(Self::BatchShare),
            _ => None,
        }
    }
}
/// 阈值模式
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum QuotaMode {
    /// 整体阈值
    Whole = 0,
    /// 单机均分阈值
    Divide = 1,
}
impl QuotaMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Whole => "WHOLE",
            Self::Divide => "DIVIDE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WHOLE" => Some(Self::Whole),
            "DIVIDE" => Some(Self::Divide),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod rate_limit_grpcv2_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct RateLimitGrpcv2Client<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RateLimitGrpcv2Client<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RateLimitGrpcv2Client<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RateLimitGrpcv2Client<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RateLimitGrpcv2Client::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 限流接口
        pub async fn service(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::RateLimitRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::RateLimitResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/polaris.metric.v2.RateLimitGRPCV2/Service",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("polaris.metric.v2.RateLimitGRPCV2", "Service"));
            self.inner.streaming(req, path, codec).await
        }
        /// 时间对齐接口
        pub async fn time_adjust(
            &mut self,
            request: impl tonic::IntoRequest<super::TimeAdjustRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TimeAdjustResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/polaris.metric.v2.RateLimitGRPCV2/TimeAdjust",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("polaris.metric.v2.RateLimitGRPCV2", "TimeAdjust"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod rate_limit_grpcv2_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RateLimitGrpcv2Server.
    #[async_trait]
    pub trait RateLimitGrpcv2: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Service method.
        type ServiceStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::RateLimitResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// 限流接口
        async fn service(
            &self,
            request: tonic::Request<tonic::Streaming<super::RateLimitRequest>>,
        ) -> std::result::Result<tonic::Response<Self::ServiceStream>, tonic::Status>;
        /// 时间对齐接口
        async fn time_adjust(
            &self,
            request: tonic::Request<super::TimeAdjustRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TimeAdjustResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct RateLimitGrpcv2Server<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> RateLimitGrpcv2Server<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for RateLimitGrpcv2Server<T>
    where
        T: RateLimitGrpcv2,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/polaris.metric.v2.RateLimitGRPCV2/Service" => {
                    #[allow(non_camel_case_types)]
                    struct ServiceSvc<T: RateLimitGrpcv2>(pub Arc<T>);
                    impl<
                        T: RateLimitGrpcv2,
                    > tonic::server::StreamingService<super::RateLimitRequest>
                    for ServiceSvc<T> {
                        type Response = super::RateLimitResponse;
                        type ResponseStream = T::ServiceStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::RateLimitRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RateLimitGrpcv2>::service(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ServiceSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/polaris.metric.v2.RateLimitGRPCV2/TimeAdjust" => {
                    #[allow(non_camel_case_types)]
                    struct TimeAdjustSvc<T: RateLimitGrpcv2>(pub Arc<T>);
                    impl<
                        T: RateLimitGrpcv2,
                    > tonic::server::UnaryService<super::TimeAdjustRequest>
                    for TimeAdjustSvc<T> {
                        type Response = super::TimeAdjustResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TimeAdjustRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RateLimitGrpcv2>::time_adjust(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TimeAdjustSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for RateLimitGrpcv2Server<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "polaris.metric.v2.RateLimitGRPCV2";
    impl<T> tonic::server::NamedService for RateLimitGrpcv2Server<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
