syntax = "proto3";

package v1;

option go_package = "github.com/pole-io/specification/source/go/api/v1/model";

option java_package = "io.pole.specification.api.v1.model";
option java_outer_classname = "NamespaceProto";

message Namespace {
  string id = 1;
  string name = 2;
  string comment = 3;
  string owners = 4;
  string token = 5;
  string ctime = 6;
  string mtime = 7;
  repeated string service_export_to = 8 [ json_name = "service_export_to" ];
  map<string, string> metadata = 9;

  uint32 total_service_count = 20 [json_name = "total_service_count"];
  uint32 total_health_instance_count = 21 [json_name = "total_health_instance_count"];
  uint32 total_instance_count = 22 [json_name = "total_instance_count"];
  uint32 total_config_file_count = 23 [json_name = "total_config_file_count"];

  bool editable = 30;
  bool deleteable = 31;
}
