syntax = "proto3";

package v1;

option go_package = "github.com/pole-io/specification/source/go/api/v1/model";

option java_package = "io.github.latticehub.pole.specification.api.v1.model";
option java_outer_classname = "CodeProto";

enum Code {
    // base module status codes
    Unknown                          = 0;
    ExecuteSuccess                   = 200000;
    DataNoChange                     = 200001;
    NoNeedUpdate                     = 200002;
    BadRequest                       = 400000;
    ParseException                   = 400001;
    EmptyRequest                     = 400002;
    BatchSizeOverLimit               = 400003;
    InvalidDiscoverResource          = 400004;
    InvalidRequestID                 = 400100;
    InvalidUserName                  = 400101;
    InvalidUserToken                 = 400102;
    InvalidParameter                 = 400103;
    EmptyQueryParameter              = 400104;
    InvalidQueryInsParameter         = 400105;
    HealthCheckNotOpen               = 400140;
    HeartbeatOnDisabledIns           = 400141;
    HeartbeatExceedLimit             = 400142;
    HeartbeatTypeNotFound            = 400143;
    InvalidMetadata                  = 400150;
    InvalidMatchRule                 = 400904;
    InvalidWorkloadCredentialRequest = 400910;

    // network relative codes
    ServicesExistedMesh   = 400170;
    ResourcesExistedMesh  = 400171;
    InvalidMeshParameter  = 400172;

    ExistedResource                  = 400201;
    NamespaceExistedServices         = 400203;
    ServiceExistedInstances          = 400204;
    ServiceExistedRoutings           = 400205;
    ServiceExistedRateLimits         = 400206;
    ExistReleasedConfig              = 400207;
    SameInstanceRequest              = 400208;
    ServiceExistedCircuitBreakers    = 400209;
    ServiceExistedAlias              = 400210;
    NamespaceExistedMeshResources    = 400211;
    NamespaceExistedCircuitBreakers  = 400212;
    ServiceSubscribedByMeshes        = 400213;
    ServiceExistedFluxRateLimits     = 400214;
    NamespaceExistedConfigGroups     = 400219;
    NamespaceExistedGovernanceRules  = 400220;
    ClientAPINotOpen                    = 400401;

    NotFoundResource                 = 404202;
    Unauthorized                        = 401000;
    NotAllowedAccess                    = 401001;
    CMDBNotFindHost                     = 404001;
    DataConflict                        = 409000;
    InstanceTooManyRequests             = 429001;
    IPRateLimit                         = 429002;
    APIRateLimit                        = 403003;
    ExecuteException                    = 500000;
    StoreLayerException                 = 500001;
    CMDBPluginException                 = 500002;
    HeartbeatException                  = 500007;
    InstanceRegisTimeout                = 500008;

    // config center status codes
    EncryptConfigFileException      = 400809;
    GroupExistActiveRelease        = 400810;
    DecryptConfigFileException      = 400811;

    // auth codes
    InvalidUserOwners          = 400410;
    InvalidUserID              = 400411;
    InvalidUserPassword        = 400412;
    InvalidUserGroupOwners     = 400420;
    InvalidUserGroupID         = 400421;
    InvalidAuthStrategyOwners  = 400430;
    InvalidAuthStrategyName    = 400431;
    InvalidAuthStrategyID      = 400432;
    InvalidPrincipalType       = 400440;

    UserExisted                             = 400215;
    UserGroupExisted                        = 400216;
    AuthStrategyRuleExisted                 = 400217;
    SubAccountExisted                       = 400218;
    NotFoundUser                            = 400312;
    NotFoundOwnerUser                       = 400313;
    NotFoundUserGroup                       = 400314;
    NotFoundAuthStrategyRule                = 400315;
    NotAllowModifyDefaultStrategyPrincipal  = 400508;
    NotAllowModifyOwnerDefaultStrategy      = 400509;;

    EmptyAutToken    = 401002;
    TokenDisabled    = 401003;
    TokenNotExisted  = 401004;
    InvalidWorkloadCredential = 401010;
    ExpiredWorkloadCredential = 401011;

    AuthTokenForbidden        = 403001;
    OperationRoleForbidden    = 403002;
    WorkloadCredentialIssueForbidden = 403010;
    StaleServiceIdentityRevision = 409010;
    WorkloadCredentialRateLimited = 429010;
    WorkloadCredentialIssuerUnavailable = 500010;
}
