syntax = "proto3";

package v1;

import "types.proto";
option go_package = "github.com/pole-io/specification/source/go/api/v1/config_manage";
option java_package = "io.pole.specification.api.v1.config.manage";
option java_outer_classname = "ConfigFileProto";

message ConfigFileGroup {
  uint64 id = 1;
  string name = 2;
  string namespace = 3;
  string comment = 4;
  string ctime = 5;
  string mtime = 7;
  string business = 8;
  string department = 9;
  map<string, string> metadata = 10;
  uint64 fileCount = 11 [ json_name = "file_count" ];
  // 删除操作标志位
  bool editable = 15;
  bool deleteable = 20;
}

message ConfigFilePersistent {
  string encoding = 1;
  string path = 2;
  string post_cmd = 3;
}

message PlaceholderValue {
  // 占位符名称
  string placeholder = 1;
  // 占位符对应的值
  repeated MatchString values = 2;
}

message ConfigFile {
  uint64 id = 1;
  string name = 2;
  string namespace = 3;
  string group = 4;
  string content = 5;
  string format = 6;
  string comment = 7;
  string status = 8;
  map<string, string> tags = 9;
  string ctime = 10;
  string mtime = 12;
  string rtime = 14;
  // 是否为加密配置文件
  bool encrypted = 16;
  // 加密算法
  string encrypt_algo = 17;
  ConfigFileSupportedClient supported_client = 18 [ json_name = "supported_client" ];
  ConfigFilePersistent persistent = 19  [ json_name = "persistent" ];

  // 文件类型
  enum ConfigFileType {
    CONFIG_FILE = 0; // 普通配置文件
    CONFIG_TEMPLATE = 1; // 配置模板
  }
  ConfigFileType config_type = 200 [ json_name = "config_type" ];
  // 如果是配置模板，还需要添加占位符对应的 value 值匹配信息
  map<string, PlaceholderValue> placeholder_value_map = 201 [ json_name = "placeholder_value_map" ];
}

enum ConfigFileSupportedClient {
  CLIENT_SDK = 0;     // 配置文件仅能被SDK拉取
  CLIENT_AGENT = 1; // 配置文件仅能被Agent拉取
  CLIENT_ALL = 2;     // 配置文件可以被SDK及Agent同时拉取
}

message ConfigFileRelease {
  uint64 id = 1;
  string name = 2;
  string namespace = 3;
  string group = 4;
  string file_name = 5 [ json_name = "file_name" ];
  string content = 6;
  string comment = 7;
  string md5 = 8;
  uint64 version = 9;
  string ctime = 10;
  string create_by = 11 [ json_name = "create_by" ];
  string mtime = 12 [ json_name = "mtime" ];
  string modify_by = 13 [ json_name = "modify_by" ];
  map<string, string>  labels = 14;
  // 当前生效配置
  bool active = 15;
  string format = 16;
  string release_description = 17 [ json_name = "release_description" ];
  string release_type = 18 [ json_name = "release_type" ];
  // 配置灰度发布时需要匹配的客户端标签信息
  repeated ClientLabel beta_labels = 19;
  // 配置文件唯一ID
  uint64 config_file_id = 20 [ json_name = "config_file_id"];
  ConfigFileSupportedClient supported_client = 21 [ json_name = "supported_client" ];
  ConfigFilePersistent persistent = 22  [ json_name = "persistent" ];

  // 文件类型
  enum ConfigFileType {
    CONFIG_FILE = 0; // 普通配置文件
    CONFIG_TEMPLATE = 1; // 配置模板
  }
  ConfigFileType config_type = 200 [ json_name = "config_type" ];
  // 如果是配置模板，还需要添加占位符对应的 value 值匹配信息
  map<string, PlaceholderValue> placeholder_value_map = 201 [ json_name = "placeholder_value_map" ];
}

message ConfigFileReleaseHistory {
  uint64 id = 1;
  string name = 2;
  string namespace = 3;
  string group = 4;
  string file_name = 5;
  string content = 6;
  string format = 7;
  string comment = 8;
  string md5 = 9;
  string type = 10;
  string status = 11;
  map<string, string>  labels = 12;
  string ctime = 13;
  string create_by = 14 [ json_name = "create_by" ];
  string mtime = 15;
  string modify_by = 16 [ json_name = "modify_by" ];
  // 配置发布失败的原因
  string reason = 17;
  string release_description = 18 [ json_name = "release_description" ];

  // 文件类型
  enum ConfigFileType {
    CONFIG_FILE = 0; // 普通配置文件
    CONFIG_TEMPLATE = 1; // 配置模板
  }
  ConfigFileType config_type = 200 [ json_name = "config_type" ];
  // 如果是配置模板，还需要添加占位符对应的 value 值匹配信息
  map<string, PlaceholderValue> placeholder_value_map = 201 [ json_name = "placeholder_value_map" ];
}

message ConfigFileTemplate {
  uint64 id = 1;
  string name = 2;
  string content = 3;
  string format = 4;
  string comment = 5;
  string ctime = 6;
  string create_by = 7;
  string mtime = 8;
  string modify_by = 9;
}

enum ConfigClientType {
  SDK = 0;
  Agent = 1;
}


message ClientWatchConfigFileRequest {
  string client_ip = 1;
  string service_name = 2;
  repeated ConfigFileRelease files = 3;
  ConfigClientType client_type = 4 [ json_name = "client_type" ];
}

message ConfigFileExportRequest {
  string namespace = 1;
  repeated string groups = 2;
  repeated string names = 3;
  repeated uint64 ids = 4;
}

message ConfigFilePublishInfo {
  string release_name = 1 [ json_name = "release_name" ];
  string namespace = 2;
  string group = 3;
  string file_name = 4 [ json_name = "file_name" ];
  string content = 5;
  string comment = 6;
  string format = 7;
  string release_description = 8 [ json_name = "release_description" ];
  string create_by = 11 [ json_name = "create_by" ];
  string modify_by = 13 [ json_name = "modify_by" ];
  map<string, string> labels = 14;
  string md5 = 15;
  // 是否为加密配置文件
  bool encrypted = 16;
  // 加密算法
  string encrypt_algo = 17;
  ConfigFilePersistent persistent = 19 [ json_name = "persistent" ];

  // 文件类型
  enum ConfigFileType {
    CONFIG_FILE = 0; // 普通配置文件
    CONFIG_TEMPLATE = 1; // 配置模板
  }
  ConfigFileType config_type = 200 [ json_name = "config_type" ];
  // 如果是配置模板，还需要添加占位符对应的 value 值匹配信息
  map<string, PlaceholderValue> placeholder_value_map = 201 [ json_name = "placeholder_value_map" ];
}

message ConfigFileGroupRequest {
  string revision = 1;
  ConfigFileGroup config_file_group = 2 [ json_name = "config_file_group" ];
  // 配置标签
  map<string, string> client_labels = 12 [ json_name = "client_labels" ];
  ConfigClientType client_type = 13 [ json_name = "client_type" ];
}

message ConfigDiscoverFilter {
  // pole.io 自定义信息
  Caller caller = 1;
}

message ConfigDiscoverRequest {
  enum ConfigDiscoverRequestType {
    UNKNOWN = 0;
    CONFIG_FILE = 1;
    CONFIG_FILE_Names = 2;
    CONFIG_FILE_GROUPS = 3;
  }
  ConfigDiscoverRequestType type = 1;
  ConfigFile file = 2 [ json_name = "file" ];
  string revision = 3;

  // pole.io 自定义信息
  ConfigDiscoverFilter filter = 500;
}

message ConfigDiscoverResponse {
  enum ConfigDiscoverResponseType {
    UNKNOWN = 0;
    CONFIG_FILE = 1;
    CONFIG_FILE_Names = 2;
    CONFIG_FILE_GROUPS = 3;
  }

  uint32 code = 1;
  string info = 2;
  string revision = 3;

  ConfigDiscoverResponseType type = 4;

  ConfigFileRelease file = 5 [ json_name = "file" ];

  repeated ConfigFileRelease file_names = 6 [json_name = "file_names" ];
  repeated ConfigFileGroup file_groups = 7 [ json_name = "file_groups" ];
}
