syntax = "proto3";

package v1;

import "google/protobuf/duration.proto";
import "types.proto";

option go_package = "github.com/pole-io/specification/source/go/api/v1/traffic_manage";
option java_package = "io.pole.specification.api.v1.traffic.manage";
option java_outer_classname = "RateLimitProto";

// 同一服务下限流规则集合
message RateLimit {
    // 限流规则唯一标识
  string id = 1;
  // 限流规则所属服务名
  string service = 2;
  // 限流规则所属命名空间
  string namespace = 3;
  // 限流规则优先级，0值最高
  uint32 priority = 5;
  // 限流类型
  // global全局限流(默认)或者local单机限流
  enum Type {
    GLOBAL = 0;
    LOCAL = 1;
  }
  Type type = 7;
  // 限流规则集合
  repeated LimitTrigger rules = 8;
  // 限流规则汇总的revision信息
  string revision = 9;
  // 是否停用该限流规则，默认启用
  bool disable = 11;
  // 限流上报方式，同时支持按固定周期上报，以及达到配额百分比后上报
  Report report = 12;
  // 分布式限流服务集群
  RateLimitCluster cluster = 16;
  // customResponse 限流触发后的响应
  CustomResponse customResponse = 17 [ json_name = "custom_response" ];
  // 限流规则创建时间
  string ctime = 20;
  // 限流规则修改时间
  string mtime = 21;
  // 限流规则标签数据
  map<string, string> metadata = 22 [ json_name = "metadata" ];
  // 操作标志位
  bool editable = 30 [ json_name = "editable" ];
  bool deleteable = 31 [ json_name = "deleteable" ];
}

// 单个限流规则信息
message LimitTrigger {
  // 限流规则名
  string name = 1;
  // 被调接口名
  MatchString method = 2;
  // 限流资源
  enum Resource {
    // 针对QPS进行限流
    QPS = 0;
    // 针对并发数进行限流
    CONCURRENCY = 1;
    // 针对系统资源进行限流
    SYSTEM = 2;
  }
  Resource resource = 3;
  // 被调的参数过滤条件，满足过滤条件才进入限流规则
  repeated MatchArgument arguments = 4;
  // 限流阈值
  // 可以有多个粒度的配置（比如同时针对秒级，分钟级，天级），匹配一个则进行限流
  // 全局限流模式下，该值为服务配额总量；单机限流模式下，该值为单个节点能处理的配额量
  repeated Amount amounts = 5;
  // 最大排队时长，单位秒
  uint32 max_queue_delay = 6 [json_name = "max_queue_delay"];
  // amount for concurrency rate-limit
  ConcurrencyAmount concurrencyAmount = 7 [ json_name = "concurrency_amount" ];
  // fallback configuration
  CustomResponse customResponse = 8 [ json_name = "custom_response" ];
  // 通配符是否合并计算，默认分开计数
  bool regex_combine = 9 [json_name = "regex_combine"];
  // 与限流集群连接失败时降级模式
  enum FailoverType {
    FAILOVER_LOCAL = 0;  // 降级成本地阈值
    FAILOVER_PASS = 1;   // 降级成直接通过
  }
  FailoverType failover = 10;
  // 限流动作，和 resource 配合决定插件名称
  string action = 11;
  // 限流阈值模
  enum AmountMode {
    GLOBAL_TOTAL = 0;   // 总体阈值
    SHARE_EQUALLY = 1;  // 单机均摊阈值
  }
  AmountMode amount_mode = 14 [json_name = "amount_mode"];
}

message MatchArgument {
  // label type for gateway request
  enum Type {
    // custom arguments
    CUSTOM = 0;
    // method, match the http post/get/put/delete or grpc method
    METHOD = 1;
    // header, match the http header, dubbo attachment, grpc header
    HEADER = 2;
    // query, match the http query, dubbo argument
    QUERY = 3;
    // caller service
    CALLER_SERVICE = 4;
    // caller host ip
    CALLER_IP =5;
    // caller instance metadata
    CALLER_METADATA = 6;
  }
  Type type = 1;
  // header key or query key
  string key = 2;
  // header value or query value
  MatchString value = 3;
}

// concurrency rate-limit amount config
message ConcurrencyAmount {
  uint32 maxAmount = 1 [ json_name = "max_amount" ];
}

// custom response text when limited
message CustomResponse {
  string code = 1 [ json_name = "code" ];
  map<string, string> headers = 2 [ json_name = "headers" ];
  string body = 3 [ json_name = "body" ];
}

// 分布式限流服务集群
message RateLimitCluster {
  string service = 1;
  // 限流规则所属命名空间
  string namespace = 2;
}

// 限流配额
message Amount {
  // 时间周期内的最大配额数
  uint32 maxAmount = 1;
  // 配额生效的时间周期，必须大于等于1s
  google.protobuf.Duration validDuration = 2;
  // 请求统计精度
  uint32 precision = 3;
  // 可选，起始限流阈值，爬坡起始值
  uint32 startAmount = 4;
  // 可选，最小限流阈值，降低时最小值
  uint32 minAmount = 5;
}

// 限流上报方式
message Report {
  // 配额固定上报周期，单位毫秒
  google.protobuf.Duration interval = 1;
  // 使用了百分之多少配额后启动一次实时上报，值范围(0,100]
  uint32 amountPercent = 2;
}
