[package]
name = "pole-specification"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license = "MIT OR Apache-2.0"
description = "Service Governance Specification."
homepage = "https://github.com/pole-io/specification"
repository = "https://github.com/pole-io/specification.git"
readme = "README.md"
keywords = ["pole", "solution", "governance", "specification", "proxyless"]
categories = ["config", "asynchronous", "development-tools"]

[dependencies]
tonic = "0.11.0"
bytes.workspace = true
prost.workspace = true
# Only necessary if using Protobuf well-known types:
prost-types.workspace = true

[build-dependencies]
prost-build = "0.12"
tonic-build = "0.11.0"
