// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.3
// source: grpcapi.proto

package service_manage

import (
	context "context"
	fault_tolerance "github.com/pole-io/specification/source/go/api/v1/fault_tolerance"
	model "github.com/pole-io/specification/source/go/api/v1/model"
	security "github.com/pole-io/specification/source/go/api/v1/security"
	traffic_manage "github.com/pole-io/specification/source/go/api/v1/traffic_manage"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoverRequest_DiscoverRequestType int32

const (
	DiscoverRequest_UNKNOWN         DiscoverRequest_DiscoverRequestType = 0
	DiscoverRequest_INSTANCE        DiscoverRequest_DiscoverRequestType = 1
	DiscoverRequest_CLUSTER         DiscoverRequest_DiscoverRequestType = 2
	DiscoverRequest_ROUTING         DiscoverRequest_DiscoverRequestType = 3
	DiscoverRequest_RATE_LIMIT      DiscoverRequest_DiscoverRequestType = 4
	DiscoverRequest_CIRCUIT_BREAKER DiscoverRequest_DiscoverRequestType = 5
	DiscoverRequest_SERVICES        DiscoverRequest_DiscoverRequestType = 6
	DiscoverRequest_NAMESPACES      DiscoverRequest_DiscoverRequestType = 12
	DiscoverRequest_FAULT_DETECTOR  DiscoverRequest_DiscoverRequestType = 13
	DiscoverRequest_LANE            DiscoverRequest_DiscoverRequestType = 100
	// 自定义路由规则
	DiscoverRequest_CUSTOM_ROUTE_RULE DiscoverRequest_DiscoverRequestType = 101
	// 就近路由规则
	DiscoverRequest_NEARBY_ROUTE_RULE DiscoverRequest_DiscoverRequestType = 102
	// 无损上下线规则
	DiscoverRequest_LOSSLESS DiscoverRequest_DiscoverRequestType = 103
	// 服务黑白名单规则
	DiscoverRequest_BLOCK_ALLOW_RULE DiscoverRequest_DiscoverRequestType = 104
	// pole.io 自定义资源信息
	DiscoverRequest_SERVICE_SUBSCRIBERS DiscoverRequest_DiscoverRequestType = 500
)

// Enum value maps for DiscoverRequest_DiscoverRequestType.
var (
	DiscoverRequest_DiscoverRequestType_name = map[int32]string{
		0:   "UNKNOWN",
		1:   "INSTANCE",
		2:   "CLUSTER",
		3:   "ROUTING",
		4:   "RATE_LIMIT",
		5:   "CIRCUIT_BREAKER",
		6:   "SERVICES",
		12:  "NAMESPACES",
		13:  "FAULT_DETECTOR",
		100: "LANE",
		101: "CUSTOM_ROUTE_RULE",
		102: "NEARBY_ROUTE_RULE",
		103: "LOSSLESS",
		104: "BLOCK_ALLOW_RULE",
		500: "SERVICE_SUBSCRIBERS",
	}
	DiscoverRequest_DiscoverRequestType_value = map[string]int32{
		"UNKNOWN":             0,
		"INSTANCE":            1,
		"CLUSTER":             2,
		"ROUTING":             3,
		"RATE_LIMIT":          4,
		"CIRCUIT_BREAKER":     5,
		"SERVICES":            6,
		"NAMESPACES":          12,
		"FAULT_DETECTOR":      13,
		"LANE":                100,
		"CUSTOM_ROUTE_RULE":   101,
		"NEARBY_ROUTE_RULE":   102,
		"LOSSLESS":            103,
		"BLOCK_ALLOW_RULE":    104,
		"SERVICE_SUBSCRIBERS": 500,
	}
)

func (x DiscoverRequest_DiscoverRequestType) Enum() *DiscoverRequest_DiscoverRequestType {
	p := new(DiscoverRequest_DiscoverRequestType)
	*p = x
	return p
}

func (x DiscoverRequest_DiscoverRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoverRequest_DiscoverRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcapi_proto_enumTypes[0].Descriptor()
}

func (DiscoverRequest_DiscoverRequestType) Type() protoreflect.EnumType {
	return &file_grpcapi_proto_enumTypes[0]
}

func (x DiscoverRequest_DiscoverRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoverRequest_DiscoverRequestType.Descriptor instead.
func (DiscoverRequest_DiscoverRequestType) EnumDescriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{1, 0}
}

type DiscoverResponse_DiscoverResponseType int32

const (
	DiscoverResponse_UNKNOWN         DiscoverResponse_DiscoverResponseType = 0
	DiscoverResponse_INSTANCE        DiscoverResponse_DiscoverResponseType = 1
	DiscoverResponse_CLUSTER         DiscoverResponse_DiscoverResponseType = 2
	DiscoverResponse_ROUTING         DiscoverResponse_DiscoverResponseType = 3
	DiscoverResponse_RATE_LIMIT      DiscoverResponse_DiscoverResponseType = 4
	DiscoverResponse_CIRCUIT_BREAKER DiscoverResponse_DiscoverResponseType = 5
	DiscoverResponse_SERVICES        DiscoverResponse_DiscoverResponseType = 6
	DiscoverResponse_NAMESPACES      DiscoverResponse_DiscoverResponseType = 12
	DiscoverResponse_FAULT_DETECTOR  DiscoverResponse_DiscoverResponseType = 13
	DiscoverResponse_LANE            DiscoverResponse_DiscoverResponseType = 100
	// 自定义路由规则
	DiscoverResponse_CUSTOM_ROUTE_RULE DiscoverResponse_DiscoverResponseType = 101
	// 就近路由规则
	DiscoverResponse_NEARBY_ROUTE_RULE DiscoverResponse_DiscoverResponseType = 102
	// 无损上下线规则
	DiscoverResponse_LOSSLESS DiscoverResponse_DiscoverResponseType = 103
	// 服务黑白名单规则
	DiscoverResponse_BLOCK_ALLOW_RULE DiscoverResponse_DiscoverResponseType = 104
	// pole.io 自定义资源信息
	DiscoverResponse_SERVICE_SUBSCRIBERS DiscoverResponse_DiscoverResponseType = 500
)

// Enum value maps for DiscoverResponse_DiscoverResponseType.
var (
	DiscoverResponse_DiscoverResponseType_name = map[int32]string{
		0:   "UNKNOWN",
		1:   "INSTANCE",
		2:   "CLUSTER",
		3:   "ROUTING",
		4:   "RATE_LIMIT",
		5:   "CIRCUIT_BREAKER",
		6:   "SERVICES",
		12:  "NAMESPACES",
		13:  "FAULT_DETECTOR",
		100: "LANE",
		101: "CUSTOM_ROUTE_RULE",
		102: "NEARBY_ROUTE_RULE",
		103: "LOSSLESS",
		104: "BLOCK_ALLOW_RULE",
		500: "SERVICE_SUBSCRIBERS",
	}
	DiscoverResponse_DiscoverResponseType_value = map[string]int32{
		"UNKNOWN":             0,
		"INSTANCE":            1,
		"CLUSTER":             2,
		"ROUTING":             3,
		"RATE_LIMIT":          4,
		"CIRCUIT_BREAKER":     5,
		"SERVICES":            6,
		"NAMESPACES":          12,
		"FAULT_DETECTOR":      13,
		"LANE":                100,
		"CUSTOM_ROUTE_RULE":   101,
		"NEARBY_ROUTE_RULE":   102,
		"LOSSLESS":            103,
		"BLOCK_ALLOW_RULE":    104,
		"SERVICE_SUBSCRIBERS": 500,
	}
)

func (x DiscoverResponse_DiscoverResponseType) Enum() *DiscoverResponse_DiscoverResponseType {
	p := new(DiscoverResponse_DiscoverResponseType)
	*p = x
	return p
}

func (x DiscoverResponse_DiscoverResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoverResponse_DiscoverResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcapi_proto_enumTypes[1].Descriptor()
}

func (DiscoverResponse_DiscoverResponseType) Type() protoreflect.EnumType {
	return &file_grpcapi_proto_enumTypes[1]
}

func (x DiscoverResponse_DiscoverResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoverResponse_DiscoverResponseType.Descriptor instead.
func (DiscoverResponse_DiscoverResponseType) EnumDescriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{2, 0}
}

type DiscoverFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OnlyHealthyInstance bool `protobuf:"varint,1,opt,name=onlyHealthyInstance,json=only_healthy_instance,proto3" json:"onlyHealthyInstance,omitempty"`
	// pole.io 自定义信息
	Caller *model.Caller `protobuf:"bytes,100,opt,name=caller,proto3" json:"caller,omitempty"`
}

func (x *DiscoverFilter) Reset() {
	*x = DiscoverFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverFilter) ProtoMessage() {}

func (x *DiscoverFilter) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverFilter.ProtoReflect.Descriptor instead.
func (*DiscoverFilter) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoverFilter) GetOnlyHealthyInstance() bool {
	if x != nil {
		return x.OnlyHealthyInstance
	}
	return false
}

func (x *DiscoverFilter) GetCaller() *model.Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

type DiscoverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    DiscoverRequest_DiscoverRequestType `protobuf:"varint,1,opt,name=type,proto3,enum=v1.DiscoverRequest_DiscoverRequestType" json:"type,omitempty"`
	Service *Service                            `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Filter  *DiscoverFilter                     `protobuf:"bytes,30,opt,name=Filter,json=filter,proto3" json:"Filter,omitempty"`
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoverRequest) GetType() DiscoverRequest_DiscoverRequestType {
	if x != nil {
		return x.Type
	}
	return DiscoverRequest_UNKNOWN
}

func (x *DiscoverRequest) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *DiscoverRequest) GetFilter() *DiscoverFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type DiscoverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code           uint32                                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info           string                                `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Type           DiscoverResponse_DiscoverResponseType `protobuf:"varint,3,opt,name=type,proto3,enum=v1.DiscoverResponse_DiscoverResponseType" json:"type,omitempty"`
	Service        *Service                              `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Instances      []*Instance                           `protobuf:"bytes,5,rep,name=instances,proto3" json:"instances,omitempty"`
	RateLimit      *traffic_manage.RateLimit             `protobuf:"bytes,7,opt,name=rateLimit,json=rate_limit,proto3" json:"rateLimit,omitempty"`
	CircuitBreaker []*fault_tolerance.CircuitBreakerRule `protobuf:"bytes,8,rep,name=circuitBreaker,json=circuit_breaker,proto3" json:"circuitBreaker,omitempty"`
	Services       []*Service                            `protobuf:"bytes,9,rep,name=services,proto3" json:"services,omitempty"`
	Namespaces     []*model.Namespace                    `protobuf:"bytes,10,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	FaultDetector  *fault_tolerance.FaultDetector        `protobuf:"bytes,11,opt,name=faultDetector,json=fault_detector,proto3" json:"faultDetector,omitempty"`
	AliasFor       *Service                              `protobuf:"bytes,21,opt,name=aliasFor,json=alias_for,proto3" json:"aliasFor,omitempty"`
	Lanes          []*traffic_manage.LaneGroup           `protobuf:"bytes,22,rep,name=lanes,proto3" json:"lanes,omitempty"`
	// 自定义路由规则内容
	CustomRouteRules []*traffic_manage.RouteRule `protobuf:"bytes,23,rep,name=customRouteRules,json=custom_route_rules,proto3" json:"customRouteRules,omitempty"`
	// 就近路由规则内容
	NearbyRouteRules []*traffic_manage.RouteRule `protobuf:"bytes,24,rep,name=nearbyRouteRules,json=nearby_route_rules,proto3" json:"nearbyRouteRules,omitempty"`
	// 无损上下线规则内容
	LosslessRules []*traffic_manage.LosslessRule `protobuf:"bytes,25,rep,name=losslessRules,json=lossless_rules,proto3" json:"losslessRules,omitempty"`
	// 服务黑白名单鉴权规则
	BlockAllowListRule []*security.BlockAllowListRule `protobuf:"bytes,26,rep,name=blockAllowListRule,json=block_allow_list_rule,proto3" json:"blockAllowListRule,omitempty"`
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_grpcapi_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoverResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DiscoverResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *DiscoverResponse) GetType() DiscoverResponse_DiscoverResponseType {
	if x != nil {
		return x.Type
	}
	return DiscoverResponse_UNKNOWN
}

func (x *DiscoverResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *DiscoverResponse) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *DiscoverResponse) GetRateLimit() *traffic_manage.RateLimit {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *DiscoverResponse) GetCircuitBreaker() []*fault_tolerance.CircuitBreakerRule {
	if x != nil {
		return x.CircuitBreaker
	}
	return nil
}

func (x *DiscoverResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *DiscoverResponse) GetNamespaces() []*model.Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *DiscoverResponse) GetFaultDetector() *fault_tolerance.FaultDetector {
	if x != nil {
		return x.FaultDetector
	}
	return nil
}

func (x *DiscoverResponse) GetAliasFor() *Service {
	if x != nil {
		return x.AliasFor
	}
	return nil
}

func (x *DiscoverResponse) GetLanes() []*traffic_manage.LaneGroup {
	if x != nil {
		return x.Lanes
	}
	return nil
}

func (x *DiscoverResponse) GetCustomRouteRules() []*traffic_manage.RouteRule {
	if x != nil {
		return x.CustomRouteRules
	}
	return nil
}

func (x *DiscoverResponse) GetNearbyRouteRules() []*traffic_manage.RouteRule {
	if x != nil {
		return x.NearbyRouteRules
	}
	return nil
}

func (x *DiscoverResponse) GetLosslessRules() []*traffic_manage.LosslessRule {
	if x != nil {
		return x.LosslessRules
	}
	return nil
}

func (x *DiscoverResponse) GetBlockAllowListRule() []*security.BlockAllowListRule {
	if x != nil {
		return x.BlockAllowListRule
	}
	return nil
}

var File_grpcapi_proto protoreflect.FileDescriptor

var file_grpcapi_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x76, 0x31, 0x1a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f,
	0x72, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x14, 0x63, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x64, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x6c, 0x61,
	0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6c, 0x6f, 0x73, 0x73, 0x6c, 0x65, 0x73, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68,
	0x0a, 0x0e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x32, 0x0a, 0x13, 0x6f, 0x6e, 0x6c, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x6f,
	0x6e, 0x6c, 0x79, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x5f, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x64,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72,
	0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x22, 0xcd, 0x03, 0x0a, 0x0f, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x2a, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0xa3, 0x02, 0x0a,
	0x13, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x52, 0x4f, 0x55, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x41, 0x54,
	0x45, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x49, 0x52,
	0x43, 0x55, 0x49, 0x54, 0x5f, 0x42, 0x52, 0x45, 0x41, 0x4b, 0x45, 0x52, 0x10, 0x05, 0x12, 0x0c,
	0x0a, 0x08, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x53, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a,
	0x4e, 0x41, 0x4d, 0x45, 0x53, 0x50, 0x41, 0x43, 0x45, 0x53, 0x10, 0x0c, 0x12, 0x12, 0x0a, 0x0e,
	0x46, 0x41, 0x55, 0x4c, 0x54, 0x5f, 0x44, 0x45, 0x54, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x10, 0x0d,
	0x12, 0x08, 0x0a, 0x04, 0x4c, 0x41, 0x4e, 0x45, 0x10, 0x64, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x55,
	0x53, 0x54, 0x4f, 0x4d, 0x5f, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x5f, 0x52, 0x55, 0x4c, 0x45, 0x10,
	0x65, 0x12, 0x15, 0x0a, 0x11, 0x4e, 0x45, 0x41, 0x52, 0x42, 0x59, 0x5f, 0x52, 0x4f, 0x55, 0x54,
	0x45, 0x5f, 0x52, 0x55, 0x4c, 0x45, 0x10, 0x66, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x4f, 0x53, 0x53,
	0x4c, 0x45, 0x53, 0x53, 0x10, 0x67, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x5f,
	0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x5f, 0x52, 0x55, 0x4c, 0x45, 0x10, 0x68, 0x12, 0x18, 0x0a, 0x13,
	0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42,
	0x45, 0x52, 0x53, 0x10, 0xf4, 0x03, 0x22, 0x04, 0x08, 0x07, 0x10, 0x0b, 0x22, 0x04, 0x08, 0x0e,
	0x10, 0x63, 0x4a, 0x04, 0x08, 0x03, 0x10, 0x05, 0x22, 0x81, 0x09, 0x0a, 0x10, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x09, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x09, 0x72, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x0a, 0x72, 0x61, 0x74, 0x65, 0x5f,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x3f, 0x0a, 0x0e, 0x63, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74,
	0x42, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x65,
	0x72, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0f, 0x63, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x5f, 0x62,
	0x72, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12,
	0x2d, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x12, 0x38,
	0x0a, 0x0d, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x61, 0x75, 0x6c, 0x74,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0e, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x08, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x46, 0x6f, 0x72, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x09, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x5f, 0x66,
	0x6f, 0x72, 0x12, 0x23, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x65, 0x73, 0x18, 0x16, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x6e, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x05, 0x6c, 0x61, 0x6e, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x10, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x17, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65,
	0x52, 0x12, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x10, 0x6e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x18, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x12, 0x6e,
	0x65, 0x61, 0x72, 0x62, 0x79, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x12, 0x37, 0x0a, 0x0d, 0x6c, 0x6f, 0x73, 0x73, 0x6c, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c,
	0x65, 0x73, 0x18, 0x19, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f,
	0x73, 0x73, 0x6c, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0e, 0x6c, 0x6f, 0x73, 0x73,
	0x6c, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x12, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x75, 0x6c, 0x65,
	0x18, 0x1a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x15,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x5f, 0x72, 0x75, 0x6c, 0x65, 0x22, 0xde, 0x02, 0x0a, 0x14, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49,
	0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4c, 0x55,
	0x53, 0x54, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x4f, 0x55, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x41, 0x54, 0x45, 0x5f, 0x4c, 0x49, 0x4d, 0x49,
	0x54, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x49, 0x52, 0x43, 0x55, 0x49, 0x54, 0x5f, 0x42,
	0x52, 0x45, 0x41, 0x4b, 0x45, 0x52, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x45, 0x52, 0x56,
	0x49, 0x43, 0x45, 0x53, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x41, 0x4d, 0x45, 0x53, 0x50,
	0x41, 0x43, 0x45, 0x53, 0x10, 0x0c, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x5f,
	0x44, 0x45, 0x54, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x10, 0x0d, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x41,
	0x4e, 0x45, 0x10, 0x64, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x5f, 0x52,
	0x4f, 0x55, 0x54, 0x45, 0x5f, 0x52, 0x55, 0x4c, 0x45, 0x10, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x4e,
	0x45, 0x41, 0x52, 0x42, 0x59, 0x5f, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x5f, 0x52, 0x55, 0x4c, 0x45,
	0x10, 0x66, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x4f, 0x53, 0x53, 0x4c, 0x45, 0x53, 0x53, 0x10, 0x67,
	0x12, 0x14, 0x0a, 0x10, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x5f,
	0x52, 0x55, 0x4c, 0x45, 0x10, 0x68, 0x12, 0x18, 0x0a, 0x13, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43,
	0x45, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x52, 0x53, 0x10, 0xf4, 0x03,
	0x22, 0x04, 0x08, 0x07, 0x10, 0x0b, 0x22, 0x04, 0x08, 0x0e, 0x10, 0x63, 0x2a, 0x04, 0x4d, 0x45,
	0x53, 0x48, 0x2a, 0x0b, 0x4d, 0x45, 0x53, 0x48, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x2a,
	0x0e, 0x46, 0x4c, 0x55, 0x58, 0x5f, 0x44, 0x42, 0x52, 0x45, 0x46, 0x52, 0x45, 0x53, 0x48, 0x2a,
	0x08, 0x46, 0x4c, 0x55, 0x58, 0x5f, 0x53, 0x44, 0x4b, 0x2a, 0x0b, 0x46, 0x4c, 0x55, 0x58, 0x5f,
	0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x4a, 0x04, 0x08, 0x0c, 0x10, 0x15, 0x32, 0xdc, 0x02, 0x0a,
	0x0b, 0x50, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x47, 0x52, 0x50, 0x43, 0x12, 0x2a, 0x0a, 0x0c,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0a, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0c, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x0c, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x12, 0x44, 0x65,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x0c,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b,
	0x0a, 0x08, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x40, 0x0a, 0x09, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3c, 0x0a,
	0x15, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x1a, 0x0c, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xae, 0x01, 0x0a, 0x14,
	0x50, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x47, 0x52, 0x50, 0x43, 0x12, 0x4a, 0x0a, 0x11, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4a, 0x0a, 0x11, 0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x83, 0x01, 0x0a,
	0x2b, 0x69, 0x6f, 0x2e, 0x70, 0x6f, 0x6c, 0x65, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x42, 0x12, 0x50, 0x6f,
	0x6c, 0x61, 0x72, 0x69, 0x73, 0x47, 0x52, 0x50, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6c,
	0x65, 0x2d, 0x69, 0x6f, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcapi_proto_rawDescOnce sync.Once
	file_grpcapi_proto_rawDescData = file_grpcapi_proto_rawDesc
)

func file_grpcapi_proto_rawDescGZIP() []byte {
	file_grpcapi_proto_rawDescOnce.Do(func() {
		file_grpcapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcapi_proto_rawDescData)
	})
	return file_grpcapi_proto_rawDescData
}

var file_grpcapi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpcapi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpcapi_proto_goTypes = []interface{}{
	(DiscoverRequest_DiscoverRequestType)(0),   // 0: v1.DiscoverRequest.DiscoverRequestType
	(DiscoverResponse_DiscoverResponseType)(0), // 1: v1.DiscoverResponse.DiscoverResponseType
	(*DiscoverFilter)(nil),                     // 2: v1.DiscoverFilter
	(*DiscoverRequest)(nil),                    // 3: v1.DiscoverRequest
	(*DiscoverResponse)(nil),                   // 4: v1.DiscoverResponse
	(*model.Caller)(nil),                       // 5: v1.Caller
	(*Service)(nil),                            // 6: v1.Service
	(*Instance)(nil),                           // 7: v1.Instance
	(*traffic_manage.RateLimit)(nil),           // 8: v1.RateLimit
	(*fault_tolerance.CircuitBreakerRule)(nil), // 9: v1.CircuitBreakerRule
	(*model.Namespace)(nil),                    // 10: v1.Namespace
	(*fault_tolerance.FaultDetector)(nil),      // 11: v1.FaultDetector
	(*traffic_manage.LaneGroup)(nil),           // 12: v1.LaneGroup
	(*traffic_manage.RouteRule)(nil),           // 13: v1.RouteRule
	(*traffic_manage.LosslessRule)(nil),        // 14: v1.LosslessRule
	(*security.BlockAllowListRule)(nil),        // 15: v1.BlockAllowListRule
	(*Client)(nil),                             // 16: v1.Client
	(*HeartbeatsRequest)(nil),                  // 17: v1.HeartbeatsRequest
	(*ServiceContract)(nil),                    // 18: v1.ServiceContract
	(*GetHeartbeatsRequest)(nil),               // 19: v1.GetHeartbeatsRequest
	(*DelHeartbeatsRequest)(nil),               // 20: v1.DelHeartbeatsRequest
	(*model.Response)(nil),                     // 21: v1.Response
	(*HeartbeatsResponse)(nil),                 // 22: v1.HeartbeatsResponse
	(*GetHeartbeatsResponse)(nil),              // 23: v1.GetHeartbeatsResponse
	(*DelHeartbeatsResponse)(nil),              // 24: v1.DelHeartbeatsResponse
}
var file_grpcapi_proto_depIdxs = []int32{
	5,  // 0: v1.DiscoverFilter.caller:type_name -> v1.Caller
	0,  // 1: v1.DiscoverRequest.type:type_name -> v1.DiscoverRequest.DiscoverRequestType
	6,  // 2: v1.DiscoverRequest.service:type_name -> v1.Service
	2,  // 3: v1.DiscoverRequest.Filter:type_name -> v1.DiscoverFilter
	1,  // 4: v1.DiscoverResponse.type:type_name -> v1.DiscoverResponse.DiscoverResponseType
	6,  // 5: v1.DiscoverResponse.service:type_name -> v1.Service
	7,  // 6: v1.DiscoverResponse.instances:type_name -> v1.Instance
	8,  // 7: v1.DiscoverResponse.rateLimit:type_name -> v1.RateLimit
	9,  // 8: v1.DiscoverResponse.circuitBreaker:type_name -> v1.CircuitBreakerRule
	6,  // 9: v1.DiscoverResponse.services:type_name -> v1.Service
	10, // 10: v1.DiscoverResponse.namespaces:type_name -> v1.Namespace
	11, // 11: v1.DiscoverResponse.faultDetector:type_name -> v1.FaultDetector
	6,  // 12: v1.DiscoverResponse.aliasFor:type_name -> v1.Service
	12, // 13: v1.DiscoverResponse.lanes:type_name -> v1.LaneGroup
	13, // 14: v1.DiscoverResponse.customRouteRules:type_name -> v1.RouteRule
	13, // 15: v1.DiscoverResponse.nearbyRouteRules:type_name -> v1.RouteRule
	14, // 16: v1.DiscoverResponse.losslessRules:type_name -> v1.LosslessRule
	15, // 17: v1.DiscoverResponse.blockAllowListRule:type_name -> v1.BlockAllowListRule
	16, // 18: v1.PolarisGRPC.ReportClient:input_type -> v1.Client
	7,  // 19: v1.PolarisGRPC.RegisterInstance:input_type -> v1.Instance
	7,  // 20: v1.PolarisGRPC.DeregisterInstance:input_type -> v1.Instance
	3,  // 21: v1.PolarisGRPC.Discover:input_type -> v1.DiscoverRequest
	17, // 22: v1.PolarisGRPC.Heartbeat:input_type -> v1.HeartbeatsRequest
	18, // 23: v1.PolarisGRPC.ReportServiceContract:input_type -> v1.ServiceContract
	19, // 24: v1.PolarisHeartbeatGRPC.BatchGetHeartbeat:input_type -> v1.GetHeartbeatsRequest
	20, // 25: v1.PolarisHeartbeatGRPC.BatchDelHeartbeat:input_type -> v1.DelHeartbeatsRequest
	21, // 26: v1.PolarisGRPC.ReportClient:output_type -> v1.Response
	21, // 27: v1.PolarisGRPC.RegisterInstance:output_type -> v1.Response
	21, // 28: v1.PolarisGRPC.DeregisterInstance:output_type -> v1.Response
	4,  // 29: v1.PolarisGRPC.Discover:output_type -> v1.DiscoverResponse
	22, // 30: v1.PolarisGRPC.Heartbeat:output_type -> v1.HeartbeatsResponse
	21, // 31: v1.PolarisGRPC.ReportServiceContract:output_type -> v1.Response
	23, // 32: v1.PolarisHeartbeatGRPC.BatchGetHeartbeat:output_type -> v1.GetHeartbeatsResponse
	24, // 33: v1.PolarisHeartbeatGRPC.BatchDelHeartbeat:output_type -> v1.DelHeartbeatsResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_grpcapi_proto_init() }
func file_grpcapi_proto_init() {
	if File_grpcapi_proto != nil {
		return
	}
	file_client_proto_init()
	file_service_proto_init()
	file_heartbeat_proto_init()
	file_contract_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpcapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcapi_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpcapi_proto_goTypes,
		DependencyIndexes: file_grpcapi_proto_depIdxs,
		EnumInfos:         file_grpcapi_proto_enumTypes,
		MessageInfos:      file_grpcapi_proto_msgTypes,
	}.Build()
	File_grpcapi_proto = out.File
	file_grpcapi_proto_rawDesc = nil
	file_grpcapi_proto_goTypes = nil
	file_grpcapi_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PolarisGRPCClient is the client API for PolarisGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PolarisGRPCClient interface {
	// 客户端上报
	ReportClient(ctx context.Context, in *Client, opts ...grpc.CallOption) (*model.Response, error)
	// 被调方注册服务实例
	RegisterInstance(ctx context.Context, in *Instance, opts ...grpc.CallOption) (*model.Response, error)
	// 被调方反注册服务实例
	DeregisterInstance(ctx context.Context, in *Instance, opts ...grpc.CallOption) (*model.Response, error)
	// 统一发现接口
	Discover(ctx context.Context, opts ...grpc.CallOption) (PolarisGRPC_DiscoverClient, error)
	// 被调方批量上报心跳
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (PolarisGRPC_HeartbeatClient, error)
	// 上报服务契约
	ReportServiceContract(ctx context.Context, in *ServiceContract, opts ...grpc.CallOption) (*model.Response, error)
}

type polarisGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewPolarisGRPCClient(cc grpc.ClientConnInterface) PolarisGRPCClient {
	return &polarisGRPCClient{cc}
}

func (c *polarisGRPCClient) ReportClient(ctx context.Context, in *Client, opts ...grpc.CallOption) (*model.Response, error) {
	out := new(model.Response)
	err := c.cc.Invoke(ctx, "/v1.PolarisGRPC/ReportClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarisGRPCClient) RegisterInstance(ctx context.Context, in *Instance, opts ...grpc.CallOption) (*model.Response, error) {
	out := new(model.Response)
	err := c.cc.Invoke(ctx, "/v1.PolarisGRPC/RegisterInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarisGRPCClient) DeregisterInstance(ctx context.Context, in *Instance, opts ...grpc.CallOption) (*model.Response, error) {
	out := new(model.Response)
	err := c.cc.Invoke(ctx, "/v1.PolarisGRPC/DeregisterInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarisGRPCClient) Discover(ctx context.Context, opts ...grpc.CallOption) (PolarisGRPC_DiscoverClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PolarisGRPC_serviceDesc.Streams[0], "/v1.PolarisGRPC/Discover", opts...)
	if err != nil {
		return nil, err
	}
	x := &polarisGRPCDiscoverClient{stream}
	return x, nil
}

type PolarisGRPC_DiscoverClient interface {
	Send(*DiscoverRequest) error
	Recv() (*DiscoverResponse, error)
	grpc.ClientStream
}

type polarisGRPCDiscoverClient struct {
	grpc.ClientStream
}

func (x *polarisGRPCDiscoverClient) Send(m *DiscoverRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *polarisGRPCDiscoverClient) Recv() (*DiscoverResponse, error) {
	m := new(DiscoverResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *polarisGRPCClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (PolarisGRPC_HeartbeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PolarisGRPC_serviceDesc.Streams[1], "/v1.PolarisGRPC/Heartbeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &polarisGRPCHeartbeatClient{stream}
	return x, nil
}

type PolarisGRPC_HeartbeatClient interface {
	Send(*HeartbeatsRequest) error
	Recv() (*HeartbeatsResponse, error)
	grpc.ClientStream
}

type polarisGRPCHeartbeatClient struct {
	grpc.ClientStream
}

func (x *polarisGRPCHeartbeatClient) Send(m *HeartbeatsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *polarisGRPCHeartbeatClient) Recv() (*HeartbeatsResponse, error) {
	m := new(HeartbeatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *polarisGRPCClient) ReportServiceContract(ctx context.Context, in *ServiceContract, opts ...grpc.CallOption) (*model.Response, error) {
	out := new(model.Response)
	err := c.cc.Invoke(ctx, "/v1.PolarisGRPC/ReportServiceContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolarisGRPCServer is the server API for PolarisGRPC service.
type PolarisGRPCServer interface {
	// 客户端上报
	ReportClient(context.Context, *Client) (*model.Response, error)
	// 被调方注册服务实例
	RegisterInstance(context.Context, *Instance) (*model.Response, error)
	// 被调方反注册服务实例
	DeregisterInstance(context.Context, *Instance) (*model.Response, error)
	// 统一发现接口
	Discover(PolarisGRPC_DiscoverServer) error
	// 被调方批量上报心跳
	Heartbeat(PolarisGRPC_HeartbeatServer) error
	// 上报服务契约
	ReportServiceContract(context.Context, *ServiceContract) (*model.Response, error)
}

// UnimplementedPolarisGRPCServer can be embedded to have forward compatible implementations.
type UnimplementedPolarisGRPCServer struct {
}

func (*UnimplementedPolarisGRPCServer) ReportClient(context.Context, *Client) (*model.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportClient not implemented")
}
func (*UnimplementedPolarisGRPCServer) RegisterInstance(context.Context, *Instance) (*model.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterInstance not implemented")
}
func (*UnimplementedPolarisGRPCServer) DeregisterInstance(context.Context, *Instance) (*model.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeregisterInstance not implemented")
}
func (*UnimplementedPolarisGRPCServer) Discover(PolarisGRPC_DiscoverServer) error {
	return status.Errorf(codes.Unimplemented, "method Discover not implemented")
}
func (*UnimplementedPolarisGRPCServer) Heartbeat(PolarisGRPC_HeartbeatServer) error {
	return status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (*UnimplementedPolarisGRPCServer) ReportServiceContract(context.Context, *ServiceContract) (*model.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportServiceContract not implemented")
}

func RegisterPolarisGRPCServer(s *grpc.Server, srv PolarisGRPCServer) {
	s.RegisterService(&_PolarisGRPC_serviceDesc, srv)
}

func _PolarisGRPC_ReportClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisGRPCServer).ReportClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisGRPC/ReportClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisGRPCServer).ReportClient(ctx, req.(*Client))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarisGRPC_RegisterInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Instance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisGRPCServer).RegisterInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisGRPC/RegisterInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisGRPCServer).RegisterInstance(ctx, req.(*Instance))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarisGRPC_DeregisterInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Instance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisGRPCServer).DeregisterInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisGRPC/DeregisterInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisGRPCServer).DeregisterInstance(ctx, req.(*Instance))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarisGRPC_Discover_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PolarisGRPCServer).Discover(&polarisGRPCDiscoverServer{stream})
}

type PolarisGRPC_DiscoverServer interface {
	Send(*DiscoverResponse) error
	Recv() (*DiscoverRequest, error)
	grpc.ServerStream
}

type polarisGRPCDiscoverServer struct {
	grpc.ServerStream
}

func (x *polarisGRPCDiscoverServer) Send(m *DiscoverResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *polarisGRPCDiscoverServer) Recv() (*DiscoverRequest, error) {
	m := new(DiscoverRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PolarisGRPC_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PolarisGRPCServer).Heartbeat(&polarisGRPCHeartbeatServer{stream})
}

type PolarisGRPC_HeartbeatServer interface {
	Send(*HeartbeatsResponse) error
	Recv() (*HeartbeatsRequest, error)
	grpc.ServerStream
}

type polarisGRPCHeartbeatServer struct {
	grpc.ServerStream
}

func (x *polarisGRPCHeartbeatServer) Send(m *HeartbeatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *polarisGRPCHeartbeatServer) Recv() (*HeartbeatsRequest, error) {
	m := new(HeartbeatsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PolarisGRPC_ReportServiceContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisGRPCServer).ReportServiceContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisGRPC/ReportServiceContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisGRPCServer).ReportServiceContract(ctx, req.(*ServiceContract))
	}
	return interceptor(ctx, in, info, handler)
}

var _PolarisGRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PolarisGRPC",
	HandlerType: (*PolarisGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportClient",
			Handler:    _PolarisGRPC_ReportClient_Handler,
		},
		{
			MethodName: "RegisterInstance",
			Handler:    _PolarisGRPC_RegisterInstance_Handler,
		},
		{
			MethodName: "DeregisterInstance",
			Handler:    _PolarisGRPC_DeregisterInstance_Handler,
		},
		{
			MethodName: "ReportServiceContract",
			Handler:    _PolarisGRPC_ReportServiceContract_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Discover",
			Handler:       _PolarisGRPC_Discover_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Heartbeat",
			Handler:       _PolarisGRPC_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpcapi.proto",
}

// PolarisHeartbeatGRPCClient is the client API for PolarisHeartbeatGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PolarisHeartbeatGRPCClient interface {
	// 批量获取心跳记录
	BatchGetHeartbeat(ctx context.Context, in *GetHeartbeatsRequest, opts ...grpc.CallOption) (*GetHeartbeatsResponse, error)
	// 批量删除心跳记录
	BatchDelHeartbeat(ctx context.Context, in *DelHeartbeatsRequest, opts ...grpc.CallOption) (*DelHeartbeatsResponse, error)
}

type polarisHeartbeatGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewPolarisHeartbeatGRPCClient(cc grpc.ClientConnInterface) PolarisHeartbeatGRPCClient {
	return &polarisHeartbeatGRPCClient{cc}
}

func (c *polarisHeartbeatGRPCClient) BatchGetHeartbeat(ctx context.Context, in *GetHeartbeatsRequest, opts ...grpc.CallOption) (*GetHeartbeatsResponse, error) {
	out := new(GetHeartbeatsResponse)
	err := c.cc.Invoke(ctx, "/v1.PolarisHeartbeatGRPC/BatchGetHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarisHeartbeatGRPCClient) BatchDelHeartbeat(ctx context.Context, in *DelHeartbeatsRequest, opts ...grpc.CallOption) (*DelHeartbeatsResponse, error) {
	out := new(DelHeartbeatsResponse)
	err := c.cc.Invoke(ctx, "/v1.PolarisHeartbeatGRPC/BatchDelHeartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolarisHeartbeatGRPCServer is the server API for PolarisHeartbeatGRPC service.
type PolarisHeartbeatGRPCServer interface {
	// 批量获取心跳记录
	BatchGetHeartbeat(context.Context, *GetHeartbeatsRequest) (*GetHeartbeatsResponse, error)
	// 批量删除心跳记录
	BatchDelHeartbeat(context.Context, *DelHeartbeatsRequest) (*DelHeartbeatsResponse, error)
}

// UnimplementedPolarisHeartbeatGRPCServer can be embedded to have forward compatible implementations.
type UnimplementedPolarisHeartbeatGRPCServer struct {
}

func (*UnimplementedPolarisHeartbeatGRPCServer) BatchGetHeartbeat(context.Context, *GetHeartbeatsRequest) (*GetHeartbeatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetHeartbeat not implemented")
}
func (*UnimplementedPolarisHeartbeatGRPCServer) BatchDelHeartbeat(context.Context, *DelHeartbeatsRequest) (*DelHeartbeatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDelHeartbeat not implemented")
}

func RegisterPolarisHeartbeatGRPCServer(s *grpc.Server, srv PolarisHeartbeatGRPCServer) {
	s.RegisterService(&_PolarisHeartbeatGRPC_serviceDesc, srv)
}

func _PolarisHeartbeatGRPC_BatchGetHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeartbeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisHeartbeatGRPCServer).BatchGetHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisHeartbeatGRPC/BatchGetHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisHeartbeatGRPCServer).BatchGetHeartbeat(ctx, req.(*GetHeartbeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarisHeartbeatGRPC_BatchDelHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelHeartbeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarisHeartbeatGRPCServer).BatchDelHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolarisHeartbeatGRPC/BatchDelHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarisHeartbeatGRPCServer).BatchDelHeartbeat(ctx, req.(*DelHeartbeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PolarisHeartbeatGRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PolarisHeartbeatGRPC",
	HandlerType: (*PolarisHeartbeatGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchGetHeartbeat",
			Handler:    _PolarisHeartbeatGRPC_BatchGetHeartbeat_Handler,
		},
		{
			MethodName: "BatchDelHeartbeat",
			Handler:    _PolarisHeartbeatGRPC_BatchDelHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcapi.proto",
}
