syntax = "proto3";

package v1;

import "types.proto";

option go_package = "github.com/pole-io/specification/source/go/api/v1/fault_tolerance";
option java_package = "io.github.latticehub.pole.specification.api.v1.fault.tolerance";
option java_outer_classname = "FaultDetectorProto";

message FaultDetectRule {
  string id = 1;
  // rule name
  string name = 2;
  // revision routing version
  string revision = 3;
  // ctime create time of the rules
  string ctime = 4;
  // mtime modify time of the rules
  string mtime = 5;
  // description simple description rules
  string description = 6;

  message DestinationService {
    string service = 1;
    string namespace = 2;
    // deprecated_filed  use api.path instead
    MatchString method = 3 [deprecated = true];
    API api = 4;
  }
  // detect protocol
  enum Protocol {
    UNKNOWN = 0;
    HTTP = 1;
    TCP = 2;
    UDP = 3;
  }
  // detect target
  DestinationService target_service = 7 [ json_name = "target_service" ];
  // priority rules priority
  uint32 priority = 8 [ json_name = "priority" ];
  // 规则标签
  map<string, string> metadata = 9 [ json_name = "metadata" ];
  // 操作标志位
  bool editable = 10 [ json_name = "editable" ];
  bool deleteable = 11 [ json_name = "deleteable" ];
  // detect sub rules
  repeated FaultDetectSubRule rules = 12;
  // namespace identifies the environment that owns this rule.
  string namespace = 13 [ json_name = "namespace" ];
}

message FaultDetectSubRule {
  // detect interval
  uint32 interval = 1;
  // detect timeout
  uint32 timeout = 2;
  // detect port
  uint32 port = 3;
  // detect protocol
  FaultDetectRule.Protocol protocol = 4;
  // http detect config
  HttpProtocolConfig http_config = 5 [ json_name = "http_config" ];
  // tcp detect config
  TcpProtocolConfig tcp_config = 6 [ json_name = "tcp_config" ];
  // udp detect config
  UdpProtocolConfig udp_config = 7 [ json_name = "udp_config" ];
  // sub rule disabled
  bool disable = 8;
}

message HttpProtocolConfig {
  string method = 1;
  string url = 2;
  message MessageHeader {
    string key = 1;
    string value = 2;
  }
  repeated MessageHeader headers = 3;
  string body = 4;
}

message TcpProtocolConfig {
  string send = 1;
  repeated string receive = 2;
}

message UdpProtocolConfig {
  string send = 1;
  repeated string receive = 2;
}
